---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
  labels:
    app: {{ build.name }}
spec:
  selector:
    app: {{ build.name }}
  type: ClusterIP
  ports:
    - name: grpc
      port: 7000
      protocol: TCP
      targetPort: grpc

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
  labels:
    app: {{ build.name }}
spec:
  replicas: {{ service.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ build.name }}
    spec:
      containers:
        - name: hypergate
          image: {{ build.images["Dockerfile"] }}
          ports:
            - name: grpc
              containerPort: 7000
